export const state = {
  backendOk: false,
  models: [],
  selectedModel: 'demo-synthetic',
  prompt: 'Fact: The number of legs on the animal that spins webs is',
  baselinePrompt: '',
  enableComparison: false,
  topK: 8,
  maxPositions: 48,
  forceDemo: false,
  loading: false,
  error: '',
  result: null,
  selectedCell: null,
  selectedPos: null,
  pinned: [],
  layerView: 'all',
  layerStep: 1,
  positionView: 'all',
  heatmapToken: null,
  diagnosticsData: null,
  showDiagnostics: false,
  comparisonResult: null,

  activeTab: 'analyze',

  chat: {
    messages: [],
    generatedRuns: [],
    selectedGeneratedToken: null,
    selectedChatAnalysisCell: null,
    maxNewTokens: 64,
    temperature: 0.0,
    topP: 1.0,
    seed: 0,
    analyzeResponse: true,
    traceGeneration: false,
    traceLayers: '8,16,24',
    topKTrace: 5,
    chatInput: '',
    generating: false,
    chatError: '',
  },

  intervention: {
    enabled: false,
    mode: 'add',
    token: '',
    sourceToken: '',
    targetToken: '',
    alpha: 1.0,
    layerStart: 8,
    layerEnd: 16,
    layerStep: 1,
    positionMode: 'all',
    selectedPositions: null,
    normalizeVector: true,
  },

  intervenedResult: null,
}
