from __future__ import annotations
import json, sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
LENSES_DIR = PROJECT_ROOT / "lenses"
LOCAL_CONFIG_PATH = PROJECT_ROOT / "configs" / "models.local.json"

def discover_pt_files() -> list[Path]:
    return sorted(LENSES_DIR.rglob("*.pt"))

def load_local_configs() -> list[dict]:
    if LOCAL_CONFIG_PATH.exists():
        return json.loads(LOCAL_CONFIG_PATH.read_text())
    return []

def save_local_configs(configs: list[dict]) -> None:
    LOCAL_CONFIG_PATH.write_text(json.dumps(configs, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {len(configs)} config(s) to {LOCAL_CONFIG_PATH}")

def main():
    pt_files = discover_pt_files()
    if not pt_files:
        print("No .pt files found in lenses/")
        print("Download a lens first: python scripts/download_lens.py --model-folder <name>")
        sys.exit(1)

    print("Discovered lens files:")
    for i, pf in enumerate(pt_files):
        print(f"  [{i}] {pf.relative_to(PROJECT_ROOT)}")

    idx = int(input("\nSelect lens file [0]: ") or "0")
    if idx < 0 or idx >= len(pt_files):
        print("Invalid selection")
        sys.exit(1)

    selected = pt_files[idx].relative_to(PROJECT_ROOT)

    config_id = input("Config ID [my-model]: ") or "my-model"
    label = input("Display label [My Model + JLens]: ") or "My Model + JLens"
    model_id = input("HF model ID or local path [org/model-name]: ") or "org/model-name"
    device = input("Device [auto]: ") or "auto"
    dtype = input("Dtype [float16]: ") or "float16"

    new_config = {
        "id": config_id,
        "label": label,
        "model_id": model_id,
        "lens_path": str(selected),
        "device": device,
        "dtype": dtype,
        "enabled": True,
        "notes": "Local config generated by setup_config.py"
    }

    existing = load_local_configs()
    match = [c for c in existing if c.get("id") == config_id]
    if match:
        print(f"Config '{config_id}' already exists.")
        overwrite = input("Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Aborted")
            return
        existing = [c for c in existing if c.get("id") != config_id]

    existing.append(new_config)
    save_local_configs(existing)
    print(f"Added config '{config_id}' with lens path {selected}")

if __name__ == "__main__":
    main()